//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automator
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int Id { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> authority_id { get; set; }
        public byte action { get; set; }
    }
}
