//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automator
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int Person_id { get; set; }
        public string Category { get; set; }
        public string First_name { get; set; }
        public string Middle_name { get; set; }
        public string Last_name { get; set; }
        public Nullable<System.DateTime> Date_of_birth_death { get; set; }
        public string Local_area { get; set; }
        public string Tahsil_Block { get; set; }
        public string District { get; set; }
        public string Sex { get; set; }
        public string Place_of_birth_death { get; set; }
        public string Name_of_mother { get; set; }
        public string Name_of_father { get; set; }
        public string Name_of_Husband { get; set; }
        public string Address_of_parents_birth__death { get; set; }
        public string Permanent_address_of_parents_deceased { get; set; }
        public string Registration_number { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Date_of_issue { get; set; }
        public Nullable<System.DateTime> Date_of_registration { get; set; }
        public string Issuing_authority { get; set; }
        public Nullable<System.DateTime> Creation_date { get; set; }
        public string Created_by { get; set; }
    }
}
