//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public string OBJECT { get; set; }
        public Nullable<int> VALUE_INT { get; set; }
        public string VALUE_CHAR { get; set; }
    }
}
